spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/871755501/sp_warehouse.git
          searchPaths: config
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
